function y = low_pass_filter(x,Fs,Fpass,Fstop,Dpass,Dstop,dens)
%LOW_PASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 14-Nov-2017 21:00:24

% Equiripple FIR Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency
% 
% Fpass = 9600;            % Passband Frequency
% Fstop = 12000;           % Stopband Frequency
% Dpass = 0.057501127785;  % Passband Ripple
% Dstop = 0.0001;          % Stopband Attenuation
% dens  = 16;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
[b,a] = tf(Hd);
y = filter(b,a,x);
% [EOF]
